# Generated by Django 4.0.2 on 2022-02-19 23:17

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='calories',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.IntegerField(default=-1),
        ),
    ]
