# Generated by Django 4.0.2 on 2022-02-20 01:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Vegetarian'), (1, 'Vegan'), (2, 'Pescetarian'), (3, 'Paleo'), (4, 'Ovo-Vegetarian'), (5, 'Ovo-Vegan'), (6, 'Ovo-Pescetarian'), (7, 'Ovo-Paleo')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(default='', max_length=200),
        ),
    ]
