# Generated by Django 4.0.2 on 2022-02-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_diet_alter_profile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.IntegerField(default=-1),
        ),
    ]
