# Generated by Django 4.0.2 on 2022-02-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calories',
            field=models.IntegerField(default=-1),
        ),
    ]
